# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp for bivariate normal distribution
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param burn burn-in length
#' @param thin the number of between-sample random numbers
#' @param mu1 N(mu1,mu2,sigma1^2,sigma2^2,rho)
#' @param mu2 N(mu1,mu2,sigma1^2,sigma2^2,rho)
#' @param sigma1 N(mu1,mu2,sigma1^2,sigma2^2,rho)
#' @param sigma2 N(mu1,mu2,sigma1^2,sigma2^2,rho)
#' @param rho N(mu1,mu2,sigma1^2,sigma2^2,rho)
#' @return a random sample of size \code{N-burn}
#' @examples
#' \dontrun{
#' X = gibbsC(10000,1000,10,0,0,1,1,0.9)
#' plot(mat, main="", cex=.5, xlab=bquote(X[1]),ylab=bquote(X[2]), ylim=range(x[,2]))
#' }
#' @export
gibbsC <- function(N, burn, thin, mu1, mu2, sigma1, sigma2, rho) {
    .Call('_StatComp22015_gibbsC', PACKAGE = 'StatComp22015', N, burn, thin, mu1, mu2, sigma1, sigma2, rho)
}

#' @title A random walk Metropolis sampler using R for t distribution using Rcpp.
#' @description A random walk Metropolis sampler using R.
#' @param n degree of freedom of t distribution
#' @param sigma standard variance of proposal distribution N(xt,sigma^2)
#' @param x0 initial value
#' @param burn burn-in length
#' @param N size of random numbers required
#' @return a random sample of size \code{N-burn}
#' @examples
#' \dontrun{
#' X = rwMetropolisC(2,1,1,100,2) #n = 2
#' a = c(0.05,seq(0.1,0.9,0.1),0.95)
#' Q = qt(a,2)
#' qqplot(a,quantile(X,a))
#' }
#' @export
rwMetropolisC <- function(n, sigma, x0, N, burn) {
    .Call('_StatComp22015_rwMetropolisC', PACKAGE = 'StatComp22015', n, sigma, x0, N, burn)
}

