# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin) {
    .Call('_StatComp22015_gibbsC', PACKAGE = 'StatComp22015', N, thin)
}

#' @title Use three inputs to predict response using Rcpp.
#' @description The prediction model is described in http://www.babelgraph.org/wp/?p=358.
#' @param n the first predictor (numeric)
#' @return square of \code{n}
#' @examples
#' \dontrun{
#' data(data)引用数据的方式
#' attach(data)
#' res <- test(n)
#' }
#' @export
test <- function(n) {
    .Call('_StatComp22015_test', PACKAGE = 'StatComp22015', n)
}

