# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp for bivariate normal distribution
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param burn burn-in length
#' @param thin the number of between-sample random numbers
#' @param mu1 N(mu1,mu2,sigma1^2,sigma2^2,rho)
#' @param mu2 N(mu1,mu2,sigma1^2,sigma2^2,rho)
#' @param sigma1 N(mu1,mu2,sigma1^2,sigma2^2,rho)
#' @param sigma2 N(mu1,mu2,sigma1^2,sigma2^2,rho)
#' @param rho N(mu1,mu2,sigma1^2,sigma2^2,rho)
#' @return a random sample of size \code{N-burn}
#' @examples
#' \dontrun{
#' X = gibbsC(10000,1000,10,0,0,1,1,0.9)
#' plot(mat, main="", cex=.5, xlab=bquote(X[1]),ylab=bquote(X[2]), ylim=range(x[,2]))
#' }
#' @export
gibbsC <- function(N, burn, thin, mu1, mu2, sigma1, sigma2, rho) {
    .Call('_StatComp22015_gibbsC', PACKAGE = 'StatComp22015', N, burn, thin, mu1, mu2, sigma1, sigma2, rho)
}

#' @title Use three inputs to predict response using Rcpp.
#' @description The prediction model is described in http://www.babelgraph.org/wp/?p=358.
#' @param n the first predictor (numeric)
#' @return square of \code{n}
#' @examples
#' \dontrun{
#' data(data)引用数据的方式
#' attach(data)
#' res <- test(n)
#' }
#' @export
test <- function(n) {
    .Call('_StatComp22015_test', PACKAGE = 'StatComp22015', n)
}

